### ISSUE TITLE
Creating Document from Large Response Takes Very Long

### ISSUE THREAD

**Issue by nitronick600** [PuerkitoBio/goquery#126] opened 2016-08-26 22:12 UTC
The following code executes a form post which returns a very large HTML table (~40k rows).  Do you have any suggestions for making this more performant?  Building the document can take up to 10 minutes.  

    timer := time.Now()

	resp, err := client.PostForm(runReportUrl, values)

	if err != nil {
		log.Println("Error posting form")
		panic(err)
	}

	log.Printf("Post Time: %s", time.Since(timer))

	contents, err := ioutil.ReadAll(resp.Body)

	if err != nil {
		panic(err)
	}
	defer resp.Body.Close()

	root, err := html.Parse(strings.NewReader(string(contents)))
	if err != nil {
		panic(err)
	}
	goquery.NewDocumentFromNode(root), complete
	log.Printf("Building goquery document took: %s", time.Since(timer))

**Comment by PuerkitoBio** [comment] 2016-08-27 01:47
Hello Nick,

10 minutes sounds crazy long though that includes the network request and reading the response. You should time since after the ReadAll to see the actual parse time (and log just the html.Parse call, where most of the time should be spent).

Assuming this is also very slow, I'm afraid you don't have many options. The net/html package has a tokenizer, which incrementally parses the document and gives you finer control, but depending on what you want to do, that may or may not be helpful. It will be lighter on memory though. That means bypassing goquery though, as goquery needs the fulld document parsed into a tree of html.Nodes.

Martin

**Comment by nitronick600** [comment] 2016-08-27 21:49
I actually found it to be memory thrash causing the massive slowdown parsing and building the document.  We were executing on Heroku and found that capping at 1Gb of memory would cause the slowdown. 

Running on a Macbook with 16Gb brought the parsing and doc building times down to a reasonable range (~15 seconds).  

The hurdle now that no amount of memory is solving is the "Find" method on a massive document like this is awfully slow. 

The following Find looks for the header of the table in question (which should be 33 elements) and with a document of this size, this will take on the order of minutes.
log.Printf("Should be 33: %d", document.Find("#tblResults > tbody > tr:nth-child(1) td,th").Size())

**Comment by PuerkitoBio** [comment] 2016-08-27 22:06
A couple of ideas:

1. the selector string is quite complex, I'd be curious to see if, say, just searching for `th` was as slow or not (I know that's not the same result you want, but just to see if that may be related to the cascadia engine having issues with that selector)

2. I found a terrible algorithm inside goquery (O(n*m) ~ O(n²)) that could be better, and should help in that case.

Does your document contain private data? If not could you share it with me, the whole html? I'd like to have a starting point and benchmark the changes.

Thanks,
Martin

**Comment by nitronick600** [comment] 2016-08-27 23:22
Unfortunately the document contains private information.  I can't even start to think of a way to properly sanitize it, either.  I'll keep that in mind, though and see if there's a way we could get you that.  The html itself is almost 3MB.  

We may be forced to implement the parser using the tokenizer instead of a proper Node based data structure like Goquery or Gokogiri

**Comment by nitronick600** [comment] 2016-08-28 01:33
I tried searching for just "th" and it still takes 12 minutes.

We're only interested in a single table, so we may try regexing it down to just the table wrapped in <html></html> and try that.

**Comment by PuerkitoBio** [comment] 2016-08-28 01:58
I'll have a branch with some optimizations for my point no. 2 that should be ready tomorrow, if you could give it a shot with that and let me know how long it takes. I'll comment here when it's ready, it is not quite there yet.

**Comment by PuerkitoBio** [comment] 2016-08-28 02:30
Ok it's ready in the `optimize-mapNodes` branch if you could give it a try (`git pull` in the goquery directory, and `git checkout optimize-mapNodes`, then re-run the test with the `th` selector so we can compare the times).

Thanks,
Martin

**Comment by nitronick600** [comment] 2016-08-28 03:28
I've found that the changes to appendWithoutDuplicates() have made a very large difference in searching through the DOM.  The `Find(th)` takes <100ms regardless of DOM size, where before it could take >10m.  

There is something going on with complex selectors.  `Find(#tblResults > tbody > tr:nth-child(1) td,th)` takes minutes, even for a smallish DOM.  

This may be something to add to the README.

**Comment by PuerkitoBio** [comment] 2016-08-28 14:34
Awesome, glad to hear that the optimization helped. For the complex selector, you say it takes minutes even for a smallish DOM, could you scrub the contents and send me the HTML of that DOM? I doubt the contents have anything to do with the slowness, so just removing the inner text of each element should be fine to reproduce the issue.

**Comment by nitronick600** [comment] 2016-08-28 17:43
Yes, I will try scraping the DOM and then run the result by my client to see if they are satisfied with the result. 

Will get back to you ASAP.

**Comment by PuerkitoBio** [comment] 2016-08-28 18:14
Cool thanks. Some ideas you may want to try too:

* Split both selectors (e.g. `Find("#tblResults > tbody > tr:nth-child(1) td").AddSelection("th")`) in case that's what's causing trouble to cascadia
* Decompose the complex selector in multiple goquery method calls (e.g. `Find("#tblResults").Find("tbody > tr:nth-child(1)").Find("td")`, or various such combinations)

I'll try generating a doc with a big table and similar structure in the meantime, to reproduce the issue.

**Comment by PuerkitoBio** [comment] 2016-08-28 18:46
I benchmarked a similar selector against a small document, and the `:nth-child` pseudo-selector seems to cause most of the slowdown. In my tests, selecting with this:

`doc.Find("#tblResults > tbody > tr").First().Find("td").Add("th")`

is about 5 times faster than with 

`doc.Find("#tblResults > tbody > tr:nth-child(1) td,th")`

That's still unlikely to be fast enough in your case with a big DOM though. Will run more tests when you send me the html, but yeah it's looking like that's in the selector engine (the `cascadia` package on which goquery depends), and obviously the bigger the document and the more complex the selector, the slower it will be - but that doesn't mean there isn't something that can be fix or improved.

**Comment by nitronick600** [comment] 2016-08-29 01:09
Hi Martin, 

I was able to achieve acceptable performance by simplifying the `Find` to 2 selectors `document.Find("#tblResults tr")`. 

From there, I did a nested `Find` for the `th` to get the header values and then parsed the rest of the table as you'd expect.  For a 42k row <table>, this brought performance from >10 minutes to ~1m15s. 

Once I close my current story, I will get you a large DOM that exercises these use cases. 

Thanks,
Nick

**Comment by nitronick600** [comment] 2016-08-30 04:22
Hi Martin, 
Unfortunately, we can't determine a strategy that will clean this DOM well enough for our client.  If you want, I can try to run a script that generates ~30 `<td>` inside a `<tr>` if you still need help creating a large enough DOM. 

Let me know if I can help.

Thanks,
Nick

**Comment by PuerkitoBio** [comment] 2016-08-30 21:54
No worries, that's fine, I saw the behaviour (I generated a doc with a few dozen tables and rows per table) although at a much smaller scale, ms instead of minutes. Surely that 30 is a typo though and that's way more than this to see it take minutes?

**Comment by nitronick600** [comment] 2016-08-30 22:01
Yes, I wasn't clear.  You need a DOM that has ~50k `<tr>`s with 30 `<td>` per `<tr>` to replicate my particular use case.

**Comment by PuerkitoBio** [comment] 2016-08-30 22:19
Ok thanks, yeah I checked cascadia's source and I think on each row it gets the parent and loops through all children to find the row's index, and then checks if that's the requested nth index (regardless if the nth index as already found). Selectors are stateless so that's not an easy fix and I'm not sure the author will be willing to do a major architecture change (which I believe would be required to make this more efficient).

I'll close this issue as you've got the workaround, but I'll open an issue on the cascadia repo once I have reproducible steps.

**Closed by PuerkitoBio** 2016-08-30 22:19 UTC

**Comment by nitronick600** [comment] 2016-08-30 22:29
It would also be good to add a note to the Wiki or something.  It's definitely possible to parse a HUGE doc in under a minute, it just takes a bit of thought.

**Comment by PuerkitoBio** [comment] 2016-08-30 22:34
Yeah good idea, there are already some tips for special cases in the wiki, I'll add something there.

**Comment by PuerkitoBio** [comment] 2016-08-31 16:19
FYI, Andy pushed a fix to cascadia that makes it almost as fast as the workaround (for nth-child(1) at least).
