### ISSUE TITLE
html entity escap error

### ISSUE THREAD

**Issue by WebFeng** [PuerkitoBio/goquery#391] opened 2021-09-07 12:20 UTC
```
doc, _ := goquery.NewDocumentFromReader(strings.NewReader("<body><!--<p></p>&lt!--[video]--&gt--></body>"))
fmt.Println(doc.Html())

// want  <html><body><!--<p></p>&lt!--[video]--&gt--></body></html> <nil>
// got <html><head></head><body><!--<p></p><!--[video]-->--></body></html> <nil>
```

**Comment by mna** [comment] 2021-09-07 23:41
Hello,

Good catch, looks like indeed the comments are not escaped when rendered (though I'm not 100% sure if it is a bug or working as intended per the html5 spec - i.e. once unescaped, it's impossible to distinguish that the `<p></p>` part should stay unescaped, while the `<!--[video]-->` part should be escaped), however this is a (potential) bug that should be reported to https://github.com/golang/go/issues?q=is%3Aissue+x%2Fnet%2Fhtml (for the `x/net/html` package), as goquery does not parse/render html itself, it uses the `golang.org/x/net/html` package for this (an html5 parser implemented by the Go team, although not part of the stdlib).

This program reproduces the issue with the `net/html` package directly, without using goquery:

```
func main() {
	root, err := html.Parse(strings.NewReader("<body><!--<p></p>&lt!--[video]--&gt--></body>"))
	if err != nil {
		log.Fatal(err)
	}

	c := findCommentNode(root)
	fmt.Printf("Comment Node Type: %d; Data: %q\n\n", c.Type, c.Data)

	fmt.Println("html.Render:")
	if err := html.Render(os.Stdout, c); err != nil {
		log.Fatal(err)
	}
	fmt.Println()
}

func findCommentNode(n *html.Node) *html.Node {
	if n.Type == html.CommentNode {
		return n
	}
	for n := n.FirstChild; n != nil; n = n.NextSibling {
		if nn := findCommentNode(n); nn != nil {
			return nn
		}
	}
	return nil
}

// Prints:
// Comment Node Type: 4; Data: "<p></p><!--[video]-->"
//
// html.Render:
// <!--<p></p><!--[video]-->-->
```

If you'd be so kind as to either link back to this issue from the net/html one, or just post the link to the issue in a comment here, I'd keep this open until there's a fix or decision made in the `net/html` repo.

Thanks,
Martin

**Comment by bensie** [comment] 2022-11-15 01:28
This _should_ be fixed in https://github.com/golang/net/commit/06994584191ebed30077b5176cefe09703557528. Can `goquery` update it's pinned dependency on `x/net` to >= v0.1.0?

**Comment by mna** [comment] 2022-11-17 02:18
Closing now that the `x/net` issue is merged.

**Closed by mna** 2022-11-17 02:18 UTC

**Comment by maileroo** [comment] 2025-01-18 08:27
Very interesting. We are trying to undo this logic as we are now having issues with conditional MSO logic as it is escaping the HTML tags.

```
<!--[if mso]>
	<v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" style="height:38px;width:145px;v-text-anchor:middle;" arcsize="20%" stroke="false" fillcolor="#152b40">
	<w:anchorlock></w:anchorlock>
	<v:textbox inset="0px,0px,0px,0px">
	<center style="color:#ffffff; font-family:"Wix Madefor Text", sans-serif; font-size:16px; font-weight:400;">
<![endif]-->
```
